"""create Phase 1A database foundation

Revision ID: 1a8fd5c3debf
Revises:
Create Date: 2026-09-20 15:00:44.222735
"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID


class MigrationUUID(sa.TypeDecorator):
    """Use native PostgreSQL UUIDs and portable strings for SQLite validation."""

    impl = sa.String
    cache_ok = True

    def load_dialect_impl(self, dialect: sa.engine.Dialect) -> sa.types.TypeEngine:
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PostgreSQLUUID(as_uuid=True))
        return dialect.type_descriptor(sa.String(36))

    def process_bind_param(self, value: uuid.UUID | str | None, dialect: sa.engine.Dialect):
        if value is None:
            return None
        identifier = value if isinstance(value, uuid.UUID) else uuid.UUID(str(value))
        return identifier if dialect.name == "postgresql" else str(identifier)

    def process_result_value(self, value: uuid.UUID | str | None, dialect: sa.engine.Dialect):
        if value is None or isinstance(value, uuid.UUID):
            return value
        return uuid.UUID(value)


revision: str = '1a8fd5c3debf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='organization_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('operating_system', sa.String(length=200), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RETIRED', name='device_status'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'hostname', name='uq_devices_org_hostname')
    )
    op.create_index('ix_devices_last_seen_at', 'devices', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_roles_org_name')
    )
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=True),
    sa.Column('actor_user_id', MigrationUUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('device_id', MigrationUUID(), nullable=True),
    sa.Column('assigned_user_id', MigrationUUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='incident_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incident_status'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_assigned_user_id'), 'incidents', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_incidents_device_id'), 'incidents', ['device_id'], unique=False)
    op.create_index('ix_incidents_opened_at', 'incidents', ['opened_at'], unique=False)
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_severity_priority', 'incidents', ['status', 'severity', 'priority'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', MigrationUUID(), nullable=False),
    sa.Column('role_id', MigrationUUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('diagnostic_runs',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('device_id', MigrationUUID(), nullable=False),
    sa.Column('incident_id', MigrationUUID(), nullable=True),
    sa.Column('diagnostic_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='diagnostic_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_runs_device_id'), 'diagnostic_runs', ['device_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_runs_incident_id'), 'diagnostic_runs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_runs_organization_id'), 'diagnostic_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_runs_status'), 'diagnostic_runs', ['status'], unique=False)
    op.create_index('ix_diagnostic_runs_status_started_at', 'diagnostic_runs', ['status', 'started_at'], unique=False)
    op.create_table('escalations',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('incident_id', MigrationUUID(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='escalation_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_incident_id'), 'escalations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_escalations_organization_id'), 'escalations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_table('diagnostic_results',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('diagnostic_run_id', MigrationUUID(), nullable=False),
    sa.Column('check_identifier', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'WARN', 'FAIL', name='diagnostic_result_status'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='diagnostic_result_severity'), nullable=False),
    sa.Column('observed_value', sa.JSON(), nullable=True),
    sa.Column('expected_value', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_run_id'], ['diagnostic_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_results_diagnostic_run_id'), 'diagnostic_results', ['diagnostic_run_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('device_id', MigrationUUID(), nullable=True),
    sa.Column('incident_id', MigrationUUID(), nullable=True),
    sa.Column('diagnostic_result_id', MigrationUUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='recommendation_priority'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='recommendation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnostic_result_id'], ['diagnostic_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_device_id'), 'recommendations', ['device_id'], unique=False)
    op.create_index(op.f('ix_recommendations_incident_id'), 'recommendations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recommendations_organization_id'), 'recommendations', ['organization_id'], unique=False)
    op.create_table('repair_actions',
    sa.Column('id', MigrationUUID(), nullable=False),
    sa.Column('organization_id', MigrationUUID(), nullable=False),
    sa.Column('device_id', MigrationUUID(), nullable=False),
    sa.Column('incident_id', MigrationUUID(), nullable=True),
    sa.Column('recommendation_id', MigrationUUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='repair_action_status'), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('executed_by', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('verification_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_actions_device_id'), 'repair_actions', ['device_id'], unique=False)
    op.create_index(op.f('ix_repair_actions_incident_id'), 'repair_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_repair_actions_organization_id'), 'repair_actions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_actions_organization_id'), table_name='repair_actions')
    op.drop_index(op.f('ix_repair_actions_incident_id'), table_name='repair_actions')
    op.drop_index(op.f('ix_repair_actions_device_id'), table_name='repair_actions')
    op.drop_table('repair_actions')
    op.drop_index(op.f('ix_recommendations_organization_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_incident_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_device_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_diagnostic_results_diagnostic_run_id'), table_name='diagnostic_results')
    op.drop_table('diagnostic_results')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_organization_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_incident_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index('ix_diagnostic_runs_status_started_at', table_name='diagnostic_runs')
    op.drop_index(op.f('ix_diagnostic_runs_status'), table_name='diagnostic_runs')
    op.drop_index(op.f('ix_diagnostic_runs_organization_id'), table_name='diagnostic_runs')
    op.drop_index(op.f('ix_diagnostic_runs_incident_id'), table_name='diagnostic_runs')
    op.drop_index(op.f('ix_diagnostic_runs_device_id'), table_name='diagnostic_runs')
    op.drop_table('diagnostic_runs')
    op.drop_table('user_roles')
    op.drop_index('ix_incidents_status_severity_priority', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.drop_index('ix_incidents_opened_at', table_name='incidents')
    op.drop_index(op.f('ix_incidents_device_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_assigned_user_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_organization_id'), table_name='devices')
    op.drop_index('ix_devices_last_seen_at', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in (
            "organization_status",
            "user_status",
            "device_status",
            "incident_severity",
            "incident_priority",
            "incident_status",
            "diagnostic_run_status",
            "diagnostic_result_status",
            "diagnostic_result_severity",
            "recommendation_priority",
            "recommendation_status",
            "repair_action_status",
            "escalation_status",
        ):
            op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
